取消发布dockerhub

diff --git a/.github/workflows/build-openppp2-binary.yml b/.github/workflows/build-openppp2-binary.yml
--- a/.github/workflows/build-openppp2-binary.yml
+++ b/.github/workflows/build-openppp2-binary.yml
@@ -13,8 +13,15 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-24.04]
-        arch: [amd64,arm64]
+        os: [ubuntu-20.04]
+        platform: 
+          - linux/amd64
+          - linux/aarch64
+        include:
+          - platform: linux/amd64
+            platform_name: linux-amd64
+          - platform: linux/aarch64
+            platform_name: linux-aarch64
 
     runs-on: ${{ matrix.os }}
     env:
@@ -30,6 +37,16 @@ jobs:
         repository: liulilittle/openppp2
         path: openppp2
         ref: main
+
+    - name: Validate ARTIFACT_NAME
+      run: |
+        PLATFORM=${{ matrix.platform_name }}
+        if [[ -z "${PLATFORM}" ]]; then
+          echo "Error: PLATFORM is empty"
+          exit 1
+        fi
+        ARTIFACT_NAME=openppp2-${PLATFORM}.zip
+        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
 
     - name: Set THIRD_PARTY_LIBRARY_DIR environment variables
       run: |
@@ -90,12 +107,8 @@ jobs:
 
     - name: Zip and list the built files
       run: |
-        ARCH=${{ matrix.arch }}
-        PLATFORM=linux-${ARCH}
         cd openppp2/bin
-        ARTIFACT_NAME=openppp2-${PLATFORM}.zip
-        zip -r $ARTIFACT_NAME ppp
-        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
+        zip -r ${{ env.ARTIFACT_NAME }} ppp
 
     - name: Archive openppp2
       uses: actions/upload-artifact@v4
@@ -105,7 +118,7 @@ jobs:
 
     - name: Set build time
       run: |
-        echo "BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
+        echo "BUILD_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
 
     - name: Create GitHub Release with Build Time
       uses: softprops/action-gh-release@v2
